export default [
  { buildingName: "World Trade Center - 1 World Trade Center", synonyms: [] },
  { buildingName: "Chanin Building", synonyms: [] },
  { buildingName: "Starrett-Lehigh Building", synonyms: [] },
  { buildingName: "The Club Row Building", synonyms: [] },
  { buildingName: "Fred F. French Bldg", synonyms: [] },
  { buildingName: "Soho Building", synonyms: [] },
  { buildingName: "Landmark", synonyms: [] },
  { buildingName: "The Helmsley Building", synonyms: [] },
  { buildingName: "Salesforce Tower", synonyms: [] },
  { buildingName: "Grace Building", synonyms: [] },
  { buildingName: "The NY Technology Exchange", synonyms: [] },
  { buildingName: "Willis Tower", synonyms: [] },
  { buildingName: "Former Bankers Trust Building", synonyms: [] },
  { buildingName: "GM Building", synonyms: [] },
  { buildingName: "The Emporis Building", synonyms: [] },
  { buildingName: "Herald Square Bldg", synonyms: [] },
  { buildingName: "The Berkeley Bldg", synonyms: [] },
  { buildingName: "Chrysler Building", synonyms: [] },
  { buildingName: "East 32nd Street Office", synonyms: [] },
  { buildingName: "Tower 570", synonyms: [] },
  { buildingName: "Citibank Building", synonyms: [] },
  { buildingName: "The Alliance Capital Building", synonyms: [] },
  { buildingName: "Seagram Building", synonyms: [] },
  { buildingName: "Art Deco Building", synonyms: [] },
  { buildingName: "Fashion Center Bldg", synonyms: [] },
  { buildingName: "Civic Opera House", synonyms: [] },
  { buildingName: "Spero Bldg", synonyms: [] },
  { buildingName: "Carnegie Hall Tower", synonyms: [] },
  { buildingName: "Institutional Investors Bldg", synonyms: [] },
  { buildingName: "International Bldg", synonyms: [] },
  { buildingName: "One Liberty Plaza", synonyms: [] },
  { buildingName: "Equitable Building", synonyms: [] },
  { buildingName: "Woolworth Bldg", synonyms: [] },
];
